name = "image-palace-frontend"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "image-palace-frontend"

[vars]
NEXT_PUBLIC_API_BASE_URL = "https://image-palace-api.fly.dev"
